name: Deploy siste oppfolgingsperiode-topic to prod

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-topic-siste-oppfolgingsperiode-to-prod.yaml
      - apps/toi-siste-oppfolgingsperiode/topic-prod.yaml

jobs:
  deploy-rapid-to-prod:
    name: Deploy siste-oppf√∏lgingsperiode-topic to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: apps/toi-siste-oppfolgingsperiode/topic-prod.yaml
    permissions:
      contents: read
      id-token: write
      security-events: write
